[platformio]
default_envs = 4d_gen4_esp32s3
src_dir = src

[env]
platform = espressif32@6.10.0
framework = arduino
monitor_speed = 115200
lib_deps =
    cone_device=symlink://../../components/cone_device
    espressif/esp32-camera@^2.0.4
lib_ldf_mode = chain+
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -DCONE_DEVICE_ENABLE_GPS=1
    -DCONE_DEVICE_ENABLE_ULTRASONIC_ARRAY=1
    -DCONE_DEVICE_ENABLE_CAMERA=1
    -DCONE_DEVICE_ENABLE_WARNING_LIGHT=1
    -DCONE_DEVICE_ENABLE_PWM_SERVO=1
    -DCONE_NODE_TELEMETRY_INTERVAL_MS=3000

[env:4d_gen4_esp32s3]
board = 4d_systems_esp32s3_gen4_r8n16
