[platformio]
default_envs = esp32dev
src_dir = src
lib_dir = ../../components

[env]
platform = espressif32@6.10.0
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -DCONE_DEVICE_ENABLE_GPS=1
    -DCONE_DEVICE_ENABLE_ULTRASONIC_ARRAY=1
    -DCONE_DEVICE_ENABLE_CAMERA=1
    -DCONE_NODE_ID=\"cone-demo-001\"
    -DCONE_NODE_TELEMETRY_INTERVAL_MS=3000

[env:esp32dev]
board = esp32dev
